### ISSUE TITLE
beginner tutorial home_page config

### ISSUE THREAD

**Issue by Prizzler** [ezsystems/developer-documentation#1076]
Hi, 
im trying ez platform v3.0.3 and started the beginner tutorial. 

page: https://doc.ezplatform.com/en/latest/tutorials/platform_beginner/3_customize_the_front_page/

the config file for editing the homepage in my case was config/packages/ezplatform_welcome_page.yaml not config/packages/ezplatform.yaml.

this was a little bit confusing.
cheers

**Comment by DominikaK** [comment]
The welcome page refers to a different page than the front page referred to in this tutorial step, see https://doc.ezplatform.com/en/master/getting_started/first_steps/#remove-welcome-page.
The tutorial mentions removing the welcome page in https://doc.ezplatform.com/en/latest/tutorials/platform_beginner/1_get_ready/

**Comment by Prizzler** [comment]
i missed that,sorry and thx
