### ISSUE TITLE
Translation of ezsystems developer-documentation into spanish language

### ISSUE THREAD

**Issue by siersod-utopian** [ezsystems/developer-documentation#180]
Greetings ezsystems Team!

I would like to help translating the documentation of ezsystems into spanish language. In order to do so, I have a couple of questions.

Should I make a new branch called Spanish and do the translation from there? an i18n/es-ES folder? or how would it be more convenient to have this translation?

Thanks in advance for your answer.

**Comment by DominikaK** [comment]
Thank you for your interest in contributing. We don't have any system for translating the documentation yet, but we are considering our options on this topic.
