### ISSUE TITLE
Limit not set in pagination

### ISSUE THREAD

**Issue by amirkoklan** [ezsystems/developer-documentation#212]
Hi, I was just wondering why in this document " https://github.com/ezsystems/developer-documentation/blob/1.13/docs/cookbook/paginating_api_search_results.md " we are not setting a limit? shouldn't we set the limit the same as "MaxPerPage"? because if not set we are taking 25 (default value ) results which is unnecessary if we want to show 10!

So I just wanted to make sure what is the reason before making a commit. if that's right just let me know and I'll commit the change

**Comment by DominikaK** [comment]
I am not quite sure what you mean here, the limit is set  with `$pager->setMaxPerPage(2);`.

This page has been reviewed recently and the code was tested and it worked as expected (paginating with two items per page, which is of course impractical, but done here for the purpose of illustration). 

Did you achieve different results? Can you elaborate on where the instruction failed?

**Comment by amirkoklan** [comment]
No. the results shown at the end are correct and no error.
but let's say we have 20 items and you want to show 2 of them on every page and as you are not using`$query->limit(2);` in every page, you are reading all 20 items from DB and pass it to twig in every page but showing only 2 of them. which I guess is the wrong way. (Performance-wise)

am I clear now ? if not I would recommend you to `{{ dump(pagerArticle) }}` in one of the pages and see there are all articles available in every page which is very bad for performance.

**Comment by DominikaK** [comment]
Thanks for the explanation, I understand now. Feel free to contribute a PR with this change :) Otherwise we'll add it to our to-do list.

**Comment by adamwojs** [comment]
@amirkoklan @DominikaK The example in documentation is correct. 

> Hi, I was just wondering why in this document " https://github.com/ezsystems/developer-documentation/blob/1.13/docs/cookbook/paginating_api_search_results.md " we are not setting a limit? shouldn't we set the limit the same as "MaxPerPage"? 

 [`\eZ\Publish\Core\Pagination\Pagerfanta\ContentSearchAdapter`](https://github.com/ezsystems/ezpublish-kernel/blob/v6.13.1/eZ/Publish/Core/Pagination/Pagerfanta/ContentSearchAdapter.php)  is responsible for setting proper `limit` and `offset` based on the "current page" and "max per page" parameters. See https://github.com/whiteoctober/Pagerfanta#adapters for more details.  

> if not I would recommend you to {{ dump(pagerArticle) }} in one of the pages and see there are all articles available in every page which is very bad for performance.

I'm sorry but I can't confirm that (verified on EZP using legacy search)
